src/Entity/Mechanics.php
<?php

namespace App\Entity;

use App\Repository\MechanicsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MechanicsRepository::class)
 */
class Mechanics
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $organization_id;

    /**
     * @ORM\Column(type="date")
     */
    private $load_ref_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $file;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrganizationId(): ?int
    {
        return $this->organization_id;
    }

    public function setOrganizationId(int $organization_id): self
    {
        $this->organization_id = $organization_id;

        return $this;
    }

    public function getLoadRefDate(): ?\DateTimeInterface
    {
        return $this->load_ref_date;
    }

    public function setLoadRefDate(\DateTimeInterface $load_ref_date): self
    {
        $this->load_ref_date = $load_ref_date;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(?string $file): self
    {
        $this->file = $file;

        return $this;
    }
}

src/Form/MechanicsType.php
<?php

namespace App\Form;

use App\Entity\Mechanics;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MechanicsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('organization_id')
            ->add('load_ref_date')
            ->add('name')
            ->add('description')
            ->add('file')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Mechanics::class,
        ]);
    }
}

src/Controller/MechanicsController.php
<?php

namespace App\Controller;

use App\Entity\Mechanics;
use App\Form\MechanicsType;
use App\Repository\MechanicsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/mechanics")
 */
class MechanicsController extends AbstractController
{
    /**
     * @Route("/", name="mechanics_index", methods={"GET"})
     */
    public function index(MechanicsRepository $mechanicsRepository): Response
    {
        return $this->render('mechanics/index.html.twig', [
            'mechanics' => $mechanicsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="mechanics_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $mechanic = new Mechanics();
        $form = $this->createForm(MechanicsType::class, $mechanic);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($mechanic);
            $entityManager->flush();

            return $this->redirectToRoute('mechanics_index');
        }

        return $this->render('mechanics/new.html.twig', [
            'mechanic' => $mechanic,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="mechanics_show", methods={"GET"})
     */
    public function show(Mechanics $mechanic): Response
    {
        return $this->render('mechanics/show.html.twig', [
            'mechanic' => $mechanic,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="mechanics_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Mechanics $mechanic): Response
    {
        $form = $this->createForm(MechanicsType::class, $mechanic);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('mechanics_index');
        }

        return $this->render('mechanics/edit.html.twig', [
            'mechanic' => $mechanic,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="mechanics_delete", methods={"POST"})
     */
    public function delete(Request $request, Mechanics $mechanic): Response
    {
        if ($this->isCsrfTokenValid('delete'.$mechanic->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($mechanic);
            $entityManager->flush();
        }

        return $this->redirectToRoute('mechanics_index');
    }
}

templates/mechanics/_delete_form.html.twig
<form method="post" action="{{ path('mechanics_delete', {'id': mechanic.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ mechanic.id) }}">
    <button class="btn">Delete</button>
</form>

templates/mechanics/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/mechanics/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Mechanics{% endblock %}

{% block body %}
    <h1>Edit Mechanics</h1>

    {{ include('mechanics/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('mechanics_index') }}">back to list</a>

    {{ include('mechanics/_delete_form.html.twig') }}
{% endblock %}

templates/mechanics/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mechanics index{% endblock %}

{% block body %}
    <h1>Mechanics index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Organization_id</th>
                <th>Load_ref_date</th>
                <th>Name</th>
                <th>Description</th>
                <th>File</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for mechanic in mechanics %}
            <tr>
                <td>{{ mechanic.id }}</td>
                <td>{{ mechanic.organizationId }}</td>
                <td>{{ mechanic.loadRefDate ? mechanic.loadRefDate|date('Y-m-d') : '' }}</td>
                <td>{{ mechanic.name }}</td>
                <td>{{ mechanic.description }}</td>
                <td>{{ mechanic.file }}</td>
                <td>
                    <a href="{{ path('mechanics_show', {'id': mechanic.id}) }}">show</a>
                    <a href="{{ path('mechanics_edit', {'id': mechanic.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('mechanics_new') }}">Create new</a>
{% endblock %}

templates/mechanics/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Mechanics{% endblock %}

{% block body %}
    <h1>Create new Mechanics</h1>

    {{ include('mechanics/_form.html.twig') }}

    <a href="{{ path('mechanics_index') }}">back to list</a>
{% endblock %}

templates/mechanics/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mechanics{% endblock %}

{% block body %}
    <h1>Mechanics</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ mechanic.id }}</td>
            </tr>
            <tr>
                <th>Organization_id</th>
                <td>{{ mechanic.organizationId }}</td>
            </tr>
            <tr>
                <th>Load_ref_date</th>
                <td>{{ mechanic.loadRefDate ? mechanic.loadRefDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ mechanic.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ mechanic.description }}</td>
            </tr>
            <tr>
                <th>File</th>
                <td>{{ mechanic.file }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('mechanics_index') }}">back to list</a>

    <a href="{{ path('mechanics_edit', {'id': mechanic.id}) }}">edit</a>

    {{ include('mechanics/_delete_form.html.twig') }}
{% endblock %}